version: '3.8'

services:
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - ${FRONTEND_HTTP_PORT}:80
            - ${FRONTEND_HTTPS_PORT}:443
        environment:
            - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
            - FRONTEND_HTTP_PORT=${FRONTEND_HTTP_PORT}
            - FRONTEND_HTTPS_PORT=${FRONTEND_HTTPS_PORT}
            - API_BASE_URL=${API_BASE_URL}
        volumes:
            - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on:
            - backend

    backend:
        image: philobiblon/backend
        ports:
            - 8080:8080
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - WIKIBASE_BASE_URL=${WIKIBASE_BASE_URL}
            - WIKIBASE_API_URL=${WIKIBASE_API_URL}
            - WIKIBASE_INDEX_URL=${WIKIBASE_INDEX_URL}
            - WIKIBASE_NICE_URL_BASE=${WIKIBASE_NICE_URL_BASE}
            - SPARQL_BASE_URL=${SPARQL_BASE_URL}
            - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
            - SPARQL_QUERY_PREFIX=${SPARQL_QUERY_PREFIX}
            - OAUTH_CONSUMER_KEY=${OAUTH_CONSUMER_KEY}
            - OAUTH_CONSUMER_SECRET=${OAUTH_CONSUMER_SECRET}
            - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
            - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
