version: '3.8'

services:
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - 3000:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    backend:
        image: philobiblon/backend
        ports:
            - 8080:8080
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env
